Update checkaip

diff --git a/checkaip b/checkaip
--- a/checkaip
+++ b/checkaip
@@ -7,6 +7,13 @@
 #		checkaip -rep my_IPlist.txt
 
 
+if [ "$#" -ne 2 ]  ; then
+	echo 
+	echo "Error: Illegal number of arguments."
+	echo 
+	exit 1
+fi
+
 if [ "$1" = "-rep" ]  ; then
 	echo "Check IP reputation"
 	echo
